# 使用官方Python基础镜像
FROM python:3.9-slim
# 设置工作目录
WORKDIR /usr/src/app
# 将项目的依赖文件复制到工作目录
COPY requirements.txt ./
# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt
# 将Python脚本复制到容器中
COPY . .
# 暴露应用的端口
EXPOSE 9090
# 运行Python应用
​​​​​​​CMD ["python", "main.py"]